# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZotCovidCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZotCovidCare
  pod 'Charts'

  target 'ZotCovidCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZotCovidCareUITests' do
    # Pods for testing
  end

end
